// Generated by CoffeeScript 1.8.0
(function() {
  define(['jquery'], function($) {
    var header_height;
    header_height = $(".header").height();
    $(".page").css("padding-top", header_height + 'px');
  });

}).call(this);
