// Generated by CoffeeScript 1.8.0
(function() {
  define(["jquery"], function($) {
    var Xin;
    if (!Xin) {
      Xin = {
        model: {},
        view: {},
        controll: {}
      };
    } else {
      return;
    }
    Xin.model.manage_list = function(data) {
      var data_item, k, prp, r_data_item, result_data, result_data_key, rows, v, _i, _j, _len, _len1;
      result_data = [];
      result_data_key = ["ID", "Name", "SimpleDesc", "AnnualEarnings"];
      rows = data.rows;
      for (_i = 0, _len = rows.length; _i < _len; _i++) {
        data_item = rows[_i];
        r_data_item = {};
        for (k in data_item) {
          v = data_item[k];
          for (_j = 0, _len1 = result_data_key.length; _j < _len1; _j++) {
            prp = result_data_key[_j];
            if (prp === k) {
              r_data_item[k] = v;
            }
          }
        }
        result_data.push(r_data_item);
      }
      return result_data;
    };
    Xin.model.getData = function(markID, data) {
      if (markID === 1) {
        return Xin.model.manage_list(data);
      }
    };
    return Xin;
  });

}).call(this);
