// Generated by CoffeeScript 1.8.0
(function() {
  define(['jquery'], function() {
    $.fn.tabs = function(optArr) {
      var tabArr;
      tabArr = optArr;
      $.each(tabArr, function(i, n) {
        return $("[data-tabname='" + n + "']").on('click', function() {
          $("[data-tabname]").removeClass('active');
          $("[data-tabcontent]").hide();
          $("[data-tabname='" + n + "']").addClass('active');
          $("[data-tabcontent='" + n + "']").show();
        });
      });
    };
  });

}).call(this);
