// Generated by CoffeeScript 1.8.0
(function() {
  requirejs.config({
    basrUrl: '../js',
    paths: {
      jquery: 'libs/jquery',
      angular: 'libs/angular.min',
      owl: 'libs/owl.carousel.min'
    },
    shim: {
      "owl": {
        deps: ["jquery"]
      }
    }
  });

  requirejs(['jquery', './app/main', './app/tab'], function($) {
    $(document).tabs(['qiye', 'media']);
  });

}).call(this);
