// Generated by CoffeeScript 1.8.0
(function() {
  requirejs.config({
    basrUrl: '../js',
    paths: {
      jquery: 'libs/jquery',
      angular: 'libs/angular.min',
      owl: 'libs/owl.carousel.min'
    },
    shim: {
      "owl": {
        deps: ["jquery"]
      }
    }
  });

  requirejs(['jquery', 'owl', './app/main'], function($) {
    var carousel_height, footer_height, header_height, link_height, window_height;
    window_height = $(window).height();
    header_height = $(".header").outerHeight();
    footer_height = $(".footer").outerHeight();
    carousel_height = $(".image-carousel").outerHeight();
    link_height = (window_height - (header_height + footer_height + carousel_height)) / 4;
    if (link_height < header_height) {
      link_height = header_height;
    }
    $("#main_menu .link").css('line-height', link_height + 'px');
    $("#index-carousel").owlCarousel({
      pagination: true,
      autoPlay: 5000,
      responsive: true,
      navigation: false,
      slideSpeed: 300,
      paginationSpeed: 400,
      singleItem: true
    });
  });

}).call(this);
