// Generated by CoffeeScript 1.8.0
(function() {
  requirejs.config({
    basrUrl: '../js',
    paths: {
      jquery: 'libs/jquery',
      angular: 'libs/angular.min',
      owl: 'libs/owl.carousel.min'
    },
    shim: {
      "owl": {
        deps: ["jquery"]
      }
    }
  });

  requirejs(['jquery', './app/wind', 'owl', './app/main'], function($, wind) {
    var add_link, others_products_owl, this_wind;
    others_products_owl = $("#others_products_list").owlCarousel({
      items: 3,
      autoPlay: 5000,
      itemsTablet: [600, 3],
      itemsMobile: false,
      pagination: false
    });
    $("#prev").on("click", function() {
      others_products_owl.trigger("owl.prev");
    });
    $("#next").on("click", function() {
      others_products_owl.trigger("owl.next");
    });
    this_wind = new wind();
    add_link = function() {
      return $("#borrow_list .link").attr('href', function() {
        var $this, id, this_link;
        $this = $(this);
        id = $this.parent().attr("data-id");
        this_link = "./Details?id=" + id;
        return this_link;
      });
    };
    this_wind.loading_data_repeat_inset("borrow_list", "/FinanceProduct/getlist", 1).done(add_link);
  });

}).call(this);
