// Generated by CoffeeScript 1.8.0
(function() {
  requirejs.config({
    basrUrl: '../js',
    paths: {
      jquery: 'libs/jquery',
      angular: 'libs/angular.min',
      owl: 'libs/owl.carousel.min'
    },
    shim: {
      "owl": {
        deps: ["jquery"]
      }
    }
  });

  requirejs(['jquery', 'owl', './app/main'], function($) {
    var login_option, register_option, user;
    login_option = {
      name: "name",
      pwd: "password",
      rememberMe: "rememberMe",
      submit: "login_submit",
      errorBox: "login_error_info",
      submit_url: "login"
    };
    user = {};
    user.login = {
      submit: function(name, pwd) {
        var user_data;
        user_data = {
          name: name,
          pwd: pwd
        };
        $.ajax({
          url: login_option.submit_url,
          type: "GET",
          dataType: "json",
          data: user_data
        }).success(function(data) {
          if (data === true) {
            window.herf.location = "usercenter.html";
          }
        }).error(function(meg) {
          console.log("data get is error");
        });
      }
    };
    $("#" + login_option.submit).on("click", function(event) {
      var errorBox, name, pwd;
      name = $("#" + login_option.name).val();
      pwd = $("#" + login_option.pwd).val();
      errorBox = $("#" + login_option.errorBox);
      if (name === "" && pwd === "") {
        errorBox.html("请输入用户名和密码");
      } else if (name === "") {
        errorBox.html("请输入用户名");
      } else if (pwd === "") {
        errorBox.html("请输入密码");
      } else if (name !== "" && pwd !== "") {
        errorBox.html("");
        user.login.submit(name, pwd);
      } else {
        errorBox.html("");
      }
    });
    register_option = {
      name: "name",
      pwd: "password",
      rememberMe: "rememberMe",
      submit: "register_submit",
      errorBox: "register_error_info",
      submit_url: "register"
    };
    $("#role_check .role").click(function() {
      var $this;
      $this = $(this);
      $("#role_check .role").not($this).removeClass('checked');
      $this.addClass("checked");
    });
  });

}).call(this);
